# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  major: 0
  minor: 1
  patch: 0
  prefix: $(major).$(minor).$(patch)
  Conf: 'Release'
  projectPath: Picsum/Picsum.csproj

steps:
 - task: DotNetCoreCLI@2
   displayName: 'Restore'
   inputs:
     command: 'restore'
     projects: Picsum/Picsum.csproj
     feedsToUse: 'select'
     vstsFeed: 'cc23d1bb-b189-4c5a-8025-9d981f84c158'
 - task: DotNetCoreCLI@2
   displayName: 'Build'
   inputs:
      command: 'build'
      arguments: '--no-restore -c $(Conf) -p:VersionPrefix=$(prefix) -p:AssemblyVersion=$(prefix)'
      projects: Picsum/Picsum.csproj

 - task: PowerShell@2
   displayName: 'Moving files'
   inputs:
    script: 'Move-Item -Path Picsum/bin/$(Conf)/*.nupkg -Destination $(Build.ArtifactStagingDirectory)'
    failOnStderr: true

 - task: PublishBuildArtifacts@1
 
   inputs:
      PathtoPublish: $(Build.ArtifactStagingDirectory)
      ArtifactName: 'artifacs'
      publishLocation: 'Container'
